Updater tests
sandboxnu/course-catalog-api pull request #10
Opened 2021-02-05 19:21 UTC by megandouli

2021-03-08 17:03 UTC, gamburgm commented on tests/updater.test.seq.ts
> +const SEM_TO_UPDATE = '202130';
Do either of these constants exist elsewhere in the codebase to import? If not this is fine.

2021-03-08 17:14 UTC, gamburgm requested changes
Only one real comment, overall looks great

2021-03-08 17:14 UTC, gamburgm commented on tests/updater.test.seq.ts
> +const SEM_TO_UPDATE = '202130';
Do either of these comments exist elsewhere in the codebase? If not that's fine.

2021-03-08 17:14 UTC, gamburgm commented on tests/updater.test.seq.ts
> +    jest.spyOn(termParser, 'parseSections').mockImplementation(mockTermParser);
Could you move as much just spying/mocking into a `beforeAll` or `beforeEach` hook either at the top of the test suite or at the top of the file?

2021-03-08 17:14 UTC, gamburgm commented on tests/updater.test.seq.ts
> +
Could you delete this empty line :^)

2021-03-09 00:35 UTC, megandouli commented on tests/updater.test.seq.ts
> +const SEM_TO_UPDATE = '202130';
do you mean `SEM_TO_UPDATE` and `EMPTY_REQ`?

2021-03-09 00:49 UTC, megandouli commented on tests/updater.test.seq.ts
> +const SEM_TO_UPDATE = '202130';
`SEM_TO_UPDATE` is just a constant in the updater atm and `EMPTY_REQ` is a relic from the old updater tests.

2021-03-09 22:26 UTC, gamburgm approved these changes
Awesome!

2021-03-10 00:40 UTC, merged