Honors Filter
sandboxnu/course-catalog-api pull request #102
Opened 2022-04-14 21:09 UTC by SimChadha

# Purpose

###### Added an honors field to each course that is true if the course has at least one honors section

<br>

# Tickets

###### https://trello.com/c/CQ602Xl2

-

# Contributors

###### Simar Chadha, Adam Koulopoulos

-
-
-
-

# Notes

###### Currently uses a hard coded timer to allow the toggle to animate before activating the filter. This is not ideal and could be done better with async/await in the future

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [x] Is passing existing tests
- [x] Has documentation and comments in code
- [ ] Has test coverage for code
- [x] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-04-20 22:10 UTC, hankewyczz requested changes
Looks good for the most part, just a few small comments & fix the tests/linting

2022-04-20 22:10 UTC, hankewyczz commented on graphql/resolvers/search.ts
```suggestion
  // Pagination parameters
```

2022-04-20 22:10 UTC, hankewyczz commented on regtests/jest.config.js
> +module.exports = {
Why was this added?

The regtests are all out of date (pre-GraphQL API), and we don't actually use any of them now

2022-04-20 22:10 UTC, hankewyczz commented on scrapers/main.ts
> +    const termDump = await classes.main(["neu"], allTermInfos);
Don't forget to add employees back

2022-04-20 22:11 UTC, hankewyczz commented on scrapers/main.ts
> +    const termDump = await classes.main(["neu"], allTermInfos);
Actually, just merge master & this should go away

2022-04-24 20:42 UTC, andrewydai requested changes
Left one comment, also we'll likely need to do an extra step to deploy this change because it has a small change to data structuring in ES (serializer file change)

2022-04-24 20:42 UTC, andrewydai commented on scrapers/main.ts
> +    const promises: [Promise<ParsedTermSR>, Promise<EmployeeWithId[]>] = [
just delete lines 28-32 this is likely from an old branch of main

2022-04-28 19:30 UTC, andrewydai approved these changes
🚀

2022-04-29 16:40 UTC, hankewyczz approved these changes
🚢

2022-04-29 19:48 UTC, merged