Update Readme
sandboxnu/course-catalog-api pull request #107
Opened 2022-04-19 19:14 UTC by hankewyczz

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br>

Update PR to explain how our scrapers work

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- https://trello.com/c/0q3bYmUp/320-improve-scrapers-story

# Contributors

###### Anyone who contributed to this PR for future reference.

- @hankewyczz 

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

-
-
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>

2022-04-19 19:15 UTC, hankewyczz commented on README.md
>  ## Installation
When reviewing - select "Display the rich diff" (on the `Files changed` tab, top-right of the file, next to the `[ ] Viewed` checkbox)

2022-04-21 19:58 UTC, SimChadha approved these changes
Really concise and easy to understand

2022-04-21 22:33 UTC, andrewydai requested changes
Looking absolute 🔥 but had some small remarks

2022-04-21 22:33 UTC, andrewydai commented on README.md
> +  termIds -->|For a single term| courses
I think "For each termId in termId's" or something to that effect is clearer than saying single.

2022-04-21 22:33 UTC, andrewydai commented on README.md
> +  dump --> DONE
For the high level and in depth graphs, I think including another step to mention propagation to ES (i.e. populateES script ran in dump processor) would be valuable because that is done in the scrape task as well

2022-04-22 00:25 UTC, hankewyczz commented
@andrewydai I didn't go in-depth about Elasticsearch - do you think this is a detailed-enough description? Between this, and your blue-green document in the `/docs` directory, I think Elasticsearch is decently documented. Do you think it's worth linking to your doc from the diagram?

2022-04-22 00:55 UTC, andrewydai commented
Yes, sorry this is really nit but I'd like a small verbage change to just mention that ES is populated from our postgres db after all the data makes it there (as opposed to the same source the db would receive, which is in memory from scraping at that point). So for example, for in depth:
`Elasticsearch indexes the data, which allows for easy searching` -> `Index data from postgres into Elasticsearch, which allows for easy searching`

2022-04-22 00:56 UTC, andrewydai approved these changes
approving anyways because I like 99.9% of this just small wordings

2022-04-22 01:06 UTC, hankewyczz commented
@andrewydai just following up to make sure this is as clear as it can be lol.

Do you think it's worth getting some outside opinions? (like Graduate team?) to make sure it makes sense in general

2022-04-24 18:39 UTC, merged