Added section filtering for Honors and Campus
sandboxnu/course-catalog-api pull request #138
Opened 2022-10-21 03:32 UTC by sebwittr

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br> Filtering by honors and campus wouldn't actually filter out the wrong sections. This PR does further filtering allowing these sections to be filtered.

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- https://trello.com/c/eG62qJDF/262-campus-section-filter

# Contributors

###### Anyone who contributed to this PR for future reference.

- @sebwittr @Lucas-Dunker 

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

- Further filters the Elastic Search result list, removing any sections that don't match the filters and any classes that may get filtered out altogether.
-
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [X ] Has documentation and comments in code
- [ ] Has test coverage for code
- [X ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-10-23 18:23 UTC, Lucas-Dunker approved these changes
Looks good!

2022-10-24 03:59 UTC, hankewyczz requested changes
Looking good, just some style/readability changes 💯

2022-10-24 03:59 UTC, hankewyczz commented on services/searcher.ts
> +    // are we filtering by honors?
Generally, we should omit comments like these - it's simple enough that the code explains itself. Comments should be reserved for areas of the code which are pretty complex/unintuitive.

2022-10-24 03:59 UTC, hankewyczz commented on services/searcher.ts
> +    }
```suggestion
    const honorsFilter = "honors" in validFilters;
```

2022-10-24 03:59 UTC, hankewyczz commented on services/searcher.ts
> +    }
```suggestion
    const campusFilter = validFilters["campus"] ?? "";
```

Same comment as above - try to remove this comment, since it doesn't add much. 

For context - the `??` is the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator). If the argument on the left is `null`, it returns the argument on the right. So, if `validFilters["campus"]` doesn't exist, it defaults to `""`

2022-10-24 03:59 UTC, hankewyczz commented on services/searcher.ts
> +    if (honorsFilter || campusFilter != "") {
```suggestion
    if (honorsFilter || campusFilter !== "") {
```

2022-10-24 03:59 UTC, hankewyczz commented on services/searcher.ts
> +
All of this should be moved into a new function. Our codebase doesn't do a very good job of it, but one function === one job. Also, a readability rule-of-thumb - if you can't fit the entire function on your screen at the same time, it's too big.

2022-10-24 03:59 UTC, hankewyczz commented on services/searcher.ts
> +            }
I'd recommend breaking this logic into a seperate function as well, and calling:
```ts
filteredResults = results.filter(this.filterFunction(honorsFilter, campusFilter));
```

with an actual name for the filter function lol

2022-10-24 03:59 UTC, hankewyczz commented on services/searcher.ts
> +      // length of filteredResults.
Personally, I also think this comment is unnecessary. 

As a general aside - if you feel differently, feel free to keep it. My main reasoning is that we now have two "sources of truth" for whats going on in the code. If the code is updated, and that person forgets to update the comment, we now have two different interpretations of what's going on, and we don't know which one to trust. And devs always forget to update comments eventually :( (eg. try reading `requests.ts`)

2022-10-24 04:01 UTC, hankewyczz commented
@Lucas-Dunker as an aside - we generally don't want to review our own PRs. Thinking about it - if you catch an error in the code, you'll just fix and commit it. And if you don't catch an error, having a green "Approved" on the PR might make other people think it's had a fresh set of eyes on it already.

2022-11-07 03:54 UTC, hankewyczz requested changes
a few more minor tweaks

as an aside, I'd appreciate it if both of you could go through this feedback together - hopefully, both of you might get something from these comments

2022-11-07 03:54 UTC, hankewyczz commented on services/searcher.ts
> +    // which ElasticSearch doesn't actually filter out.
```suggestion
  /** 
   * Perform extra filtering if Honors or Campus Filters are being applied.
   * Elasticsearch will return ALL sections for a class if ANY of its sections match the filter.
   * eg. if a class has 100 sections and 1 of them is Honors, applying the Honors filter
   *       in Elasticsearch will return all 100 sections.
   * This function only returns the sections which match the filter.
   */
  filterResults(filters, results): SearchResult[] {
```

For function comments, we prefer [JSDoc](https://jsdoc.app/) - that way, when someone hovers over the function name, they'll see the comment. (I know the majority of our codebase doesn't use that, but we want to write better code going forward & slowly refactor the old code to match)

2022-11-07 03:54 UTC, hankewyczz commented on services/searcher.ts
> +      filteredResults = [];
```suggestion
    if (!honorsFilter && campusFilter === "") {
      return results;
    }
    .... // handle the filtering here
```

Instead of wrapping the "we need to filter further" case in an `if` block, just write a simple `if` to see if we DON'T need to filter further. This is preferred because:
- we don't have to wrap a large chunk of code in a block - it's simpler & easier to read (and less indentation)
- instead of assigning `filteredResults` to `results` and conditionally changing that, just assign `const filteredResults = []`. It's simpler, doesn't require a comment explaining it, and allows you to use `const`

2022-11-07 03:54 UTC, hankewyczz commented on services/searcher.ts
> +          // filter the sections for each result
Generally, we should omit comments like these - it's simple enough that the code explains itself. Comments should be reserved for areas of the code which are pretty complex/unintuitive.

I'm not going to leave a review comment on each spot like this - pls just go through and check all the comments to see if they generally meet the classification above.

2022-11-07 03:54 UTC, hankewyczz commented on services/searcher.ts
> +    const honorsFilter: boolean = validFilters["honors"] ? true : false;
```suggestion
    const honorsFilter = validFilters["honors"] ?? false;
```

We want to use the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) here.

Using a conditional in the format 
```js
if (condition) {
   return true
} else {
   return false
}
```
is generally a bad design - you could just return the `condition`. However, in this case, the conditional is necessary for Javascript to cast the type to a boolean. We want to avoid that, since that sort of casting can mask errors (eg. if for some reason `"honors": "error"`, the string `"error"` would cast to `true` (since it's non-empty). However, that should break our code, since its a completely unexpected value). 

Note - read the [Examples page for the `??` operator - it's quick](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#examples)

2022-11-07 03:54 UTC, hankewyczz commented on services/searcher.ts
> +    const campusFilter: string = "" + (validFilters["campus"] ?? "");
```suggestion
    const campusFilter = validFilters["campus"] ?? "";
```

Same comment as above - we don't want to use the `"" + ...` pattern to forcibly convert `validFilters["campus"]` to a string, since that can mask errors. Also, the explicit type isn't necessary here - TS is good at figuring out basic types like this (you can leave it, ofc, just figured it's worth pointing out)

2022-11-07 03:54 UTC, hankewyczz commented on services/searcher.ts
> +  filterSection(
Can we add a JSDoc comment for this function?

2022-11-21 14:13 UTC, hankewyczz approved these changes
looks great!! 💯

2022-12-16 23:45 UTC, hankewyczz commented
@sebwittr When you get a chance, could you merge this branch with the updated master branch?

2023-01-25 22:06 UTC, hankewyczz commented
Fixed in #156

2023-01-25 22:06 UTC, closed without merging