Add `POSTGRES_PASSWORD`
sandboxnu/course-catalog-api pull request #155
Opened 2023-01-24 03:43 UTC by hankewyczz

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br>

- https://hub.docker.com/_/postgres
- https://www.postgresql.org/docs/14/auth-trust.html

With our PSQL upgrade (#149), the default will throw an error if no Postgres password is provided. 

For local development, we don't use a password (this is not true for prod/staging). While we *could* override this setting with no issue, it's safer to default to a password. 

This only affects each user's local development environment, which is at very low-risk for access and/or misuse (all data is public anyways). 

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- N/A

# Contributors

###### Anyone who contributed to this PR for future reference.

- @hankewyczz 

# Checklist

- [x] Filled out PR template :wink:
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2023-01-24 04:57 UTC, hankewyczz commented on prisma/schema.prisma
> -  provider        = "prisma-client-js"
Automatic formatting changes

2023-01-24 04:57 UTC, hankewyczz commented on infrastructure/dev/docker-compose-server.yml
> +    image: postgres:11.17-bullseye
Updated to match the other docker-compose file (which is more frequently used). This file is rarely (if ever) used, and only for local dev

2023-01-25 22:10 UTC, hankewyczz commented on .github/workflows/docker.yaml
> -          POSTGRES_PASSWORD:
By removing this, we allow the `POSTGRESS_PASSWORD` in the user's local environment to take precedence

2023-01-25 22:10 UTC, hankewyczz commented on template.env
> +POSTGRES_PASSWORD=default_password
To test these changes:
- delete your docker PSQL container
- `docker stop dev_postgresql_1 && docker rm dev_postgresql_1`
- add a password to your env file (can be anything)
- run `yarn dev:docker`
- run the scrape and updater again to populate the new database

2023-02-02 23:46 UTC, Lucas-Dunker approved these changes
Nothin to say

2023-02-05 21:30 UTC, soulwa requested changes
current setup for passing environment variables doesn't fix the issue (at least, on my machine). 

there's a few ways to fix this, but the only one that I am aware of that keeps parity with the prisma environment is to add the `env_file` field to `docker-compose.yml` and have it reference the `.env` in the root of the project. only downside to this is polluting our container's environment (eg. the twilio variables would also get passed).

we could also pass it as an argument to `docker-compose up` when running `yarn dev:docker`, but this means you would need to always run the container through `yarn`. this is because the variables in `.env` are only local env variables when running a `yarn` commend.

i'll push something up which shows what the first solution would look like once I've verified that it works. would probably also be good to see that this works on at least another member's machine so that we know this is a more permanent solution.

2023-02-07 02:22 UTC, hankewyczz commented
You're right  — @Lucas-Dunker  could you please read this and re-review? I had an issue in my reproduction instructions (you also have to delete the Docker volume associated with the PSQL container).

> there's a few ways to fix this, but the only one that I am aware of that keeps parity with the prisma environment is to add the `env_file` field to `docker-compose.yml` and have it reference the `.env` in the root of the project. only downside to this is polluting our container's environment (eg. the twilio variables would also get passed).

I can confirm that this works. I'm not a massive fan of this behavior, but I don't see a significantly better approach.

2023-03-01 03:42 UTC, Lucas-Dunker approved these changes
Can confirm that this approach works on my machine as well, I'm able to make valid queries on the graphQL server like before; since the `docker-compose.yml` file now references the env file instead of a password, how/where does the container actually grab the password for authentication? Does it just automatically grab the password from the local environment?

2023-03-02 02:34 UTC, hankewyczz commented
> Can confirm that this approach works on my machine as well, I'm able to make valid queries on the graphQL server like before; since the `docker-compose.yml` file now references the env file instead of a password, how/where does the container actually grab the password for authentication? Does it just automatically grab the password from the local environment?

Yes and no — it inherits all environment arguments from the `.env` file, not necessarily the local environment (you can set environment variables outside of the `.env` file)

2023-03-03 21:57 UTC, soulwa approved these changes

2023-03-03 21:58 UTC, soulwa commented
new setup works for me, after nuking my docker setup and re-performing the backend setup process, so lgtm

2023-03-03 22:38 UTC, sebwittr approved these changes
Looks good to me

2023-03-12 22:11 UTC, merged