Update PR template
sandboxnu/course-catalog-api pull request #165
Opened 2023-03-16 16:13 UTC by hankewyczz

# Purpose

_In 2-3 sentences - what does this code actually do, and why?_

Updates the PR template we use for PRs to reflect changes in the team's review process (use primary/secondary reviewers)

# Tickets

_What Trello tickets (if any) are associated with this PR?_

N/A

# Contributors

_Who worked on this PR? Tag them with their Github `@username` for future reference_

- @hankewyczz 

# Feature List

_Expand on the purpose - what does this code do, and how? This should be a list of the changes, more in-depth and technical_

- Moves `pull_request_template.md` to the `.github` directory (for organization purposes)
- Updates that file with a new format

# Reviewers

Primary reviewer:
- Pick one primary reviewer
  - the team member with the most relevant knowledge about the code area this PR touches.
  - **NOT** an author of the PR
  - If the primary reviewer is the project lead, _select two primary reviewers_
    - Goal: facilitate knowledge transfer to other team members
  - Primary reviewers **are required to approve the PR** before it can be merged.

**Primary**: @sebwittr @Lucas-Dunker 

Secondary reviewers:
- Pick as many as appropriate
- Anyone who would benefit from reading the PR to learn.

**Secondary**: @pranavphadke1 @allychao @soulwa

2023-03-18 18:53 UTC, pranavphadke1 approved these changes

2023-03-22 21:10 UTC, Lucas-Dunker requested changes
Other than what I said, looks good!

2023-03-22 21:10 UTC, Lucas-Dunker commented on .github/pull_request_template.md
> +  - the team member with the most relevant knowledge about the code area this PR touches.
```suggestion
  - The team member with the most relevant knowledge about the code area this PR touches
```

We probably want all the formatting to be consistent (capital letters for titles, no periods)

2023-03-22 21:10 UTC, Lucas-Dunker commented on .github/pull_request_template.md
> +  - Primary reviewers **are required to approve the PR** before it can be merged.
```suggestion
  - Primary reviewers **are required to approve the PR** before it can be merged
```

Same concept as above

2023-03-22 21:10 UTC, Lucas-Dunker commented on .github/pull_request_template.md
> +- Anyone who would benefit from reading the PR to learn.
```suggestion
- Anyone who would benefit from reading the PR to learn
```

Same concept as above

2023-03-23 17:52 UTC, sebwittr approved these changes
looks good

2023-03-28 01:01 UTC, allychao approved these changes
Not sure if we use this template for frontend repo as well, but if we do we should have a section for a picture of what was worked on. Otherwise lgtm!

2023-03-28 14:30 UTC, Lucas-Dunker approved these changes

2023-03-29 20:53 UTC, merged