Change bulkUpserter retry period and prevent erroring silently
sandboxnu/course-catalog-api pull request #172
Opened 2023-04-02 18:39 UTC by sebwittr

# Purpose

_In 2-3 sentences - what does this code actually do, and why?_

Our bulkIndex was failing silently, so now it will catch and log the errors. We also slightly increased the retry period in case it needed more time. 

# Tickets

_What Trello tickets (if any) are associated with this PR?_

# Contributors

@sebwittr 

Use the **"Assignees"** feature in Github

# Feature List

_Expand on the purpose - what does this code do, and how? This should be a list of the changes, more in-depth and technical_

- Increased retry period to 1000 to bulkIndex
- Added a try/catch to see if it failed, and logged it
-

# Notes (Optional)

_Is there anything reviewers should note? Do we need to add something later? Any followups? Was this ticket easier/harder than predicted?_

# Reviewers

**Primary**:

@hankewyczz  @Lucas-Dunker

2023-04-03 13:56 UTC, hankewyczz requested changes

2023-04-03 13:56 UTC, hankewyczz commented on utils/elastic.ts
> +        try {
We should toss this functionality into `retryBulkQuery`

2023-04-05 04:31 UTC, Lucas-Dunker approved these changes
LGTM 🙏

2023-04-09 19:00 UTC, sebwittr commented on utils/elastic.ts
> +        try {
retryBulkQuery already has some try catch functionality, and bulkIndexFromMap was the one that was silently erroring.

2023-04-09 20:08 UTC, hankewyczz commented on utils/elastic.ts
> +        if (i == MAX_RETRY_ATTEMPTS - 1) {
```suggestion
        if (i === MAX_RETRY_ATTEMPTS - 1) {
```

2023-04-28 16:39 UTC, hankewyczz approved these changes

2023-04-28 19:42 UTC, merged