Remove manual bulk upsert from dumpProcessor
sandboxnu/course-catalog-api pull request #173
Opened 2023-04-05 23:40 UTC by hankewyczz

# Purpose

_In 2-3 sentences - what does this code actually do, and why?_

We used to be manually hand-crafting SQL queries, which is easy to break and a security issue. All around - a messy piece of our data processing. This replaces that. 

# Tickets

_What Trello tickets (if any) are associated with this PR?_

- https://trello.com/c/mZ3B6bYS/350-replace-bulkupsert-mechanism-for-dumpprocessor

# Notes (Optional)

_Is there anything reviewers should note? Do we need to add something later? Any followups? Was this ticket easier/harder than predicted?_

An "upsert" is a combination of an "insert" and an "update" in SQL. 
- If the object already exists - update it
- If the object doesn't already exist - create it

When we process our data, we want to "upsert" our courses and sections. However, Prisma doesn't have a way to do this in bulk.

Currently, we are using a hand-crafted query. This can run upserts on multiple objects in a single query. However, this is fragile, isn't type-safe, and is generally frowned upon as bad practice. 

Instead, we can use `prisma.upsert` to upsert them one-by-one. This comes at a performance cost - this operation takes 60-80% longer (from my basic tests). However, we don't care!

- The scraper runs once a day, so as long as upserting takes less than 24 hours, this doesn't matter
- The updater runs every 5 minutes - same thing as above

There's a caveat in the case of the updater - the updater sends out SMS notifications for seats becoming free. Obviously, we want to send these out as fast as possible. As part of this PR, I changed the order of execution — notifications are now sent BEFORE the data is processed & inserted into the database and Elasticsearch.

# Reviewers

Secondary reviewers:

- Pick as many as appropriate — anyone who would benefit from reading the PR
  - Tag them using their Github usernames below

**Secondary**:

2023-04-06 17:32 UTC, hankewyczz commented on services/dumpProcessor.ts
> -  CHUNK_SIZE: number;
We stopped using this a while ago, and just never removed it.

2023-04-06 17:32 UTC, hankewyczz commented on services/dumpProcessor.ts
> +  ): Prisma.SectionUncheckedCreateInput {
It turns out Prisma has a type that includes the `classHash`, so we should use it instead of making up our own type.

2023-04-06 17:32 UTC, hankewyczz commented on services/updater.ts
> +    await sendNotifications(
Send notifications BEFORE the dump processor, so that users get the quickest possible notification.

2023-04-06 17:32 UTC, hankewyczz commented on tests/database/dbTestEnv.ts
> +    this.databaseUrl = `postgresql://postgres:${process.env.POSTGRES_PASSWORD}@localhost:5432/searchneu_test?schema=${this.schema}`;
This should have been updated when I made the PSQL password changes. This only affects testing in dev environments — our tests on github were unaffected

2023-04-06 17:32 UTC, hankewyczz commented on tests/general/utils.test.ts
> -import dumpProcessor from "../../services/dumpProcessor";
I deleted all of the functions being tested in this file, so it's now useless to us.

2023-04-11 02:59 UTC, hankewyczz commented on services/updater.ts
>      // 5 min if prod, 30 sec if dev.
change time in comment

2023-04-11 03:00 UTC, tiingweii-shii requested changes

2023-04-11 03:00 UTC, tiingweii-shii commented on services/dumpProcessor.ts
> +      await Promise.all(upsertQueries);
Abstraction 👾

2023-04-11 15:06 UTC, hankewyczz commented on services/dumpProcessor.ts
> +      await Promise.all(upsertQueries);
I tried today — you can't abstract this pattern without sacrificing Prisma's type saftey and using a few `any` types, which I'd rather avoid.

2023-04-11 19:22 UTC, hankewyczz commented on services/updater.ts
>      // 5 min if prod, 30 sec if dev.
```suggestion
    // 5 min if prod, 1 min if dev.
```

2023-04-16 20:38 UTC, sebwittr approved these changes
Looks good for the most part, just had a question about doing notifications before the dumpProcessor

2023-04-16 20:38 UTC, sebwittr commented on services/updater.ts
> +    await sendNotifications(
Doesn't some of the data from the dump processor need to be used for the notifications?

2023-04-20 04:53 UTC, Lucas-Dunker requested changes
Looks great to me aside from a few questions, god bless prisma upsert 🙏

2023-04-20 04:53 UTC, Lucas-Dunker commented on services/dumpProcessor.ts
> +    const groupedCourses = _.chunk(processedCourses, 2000);
Do we still wanna use lodash here, or should we start [using the natural JS replacements](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore)?

2023-04-20 04:53 UTC, Lucas-Dunker commented on services/dumpProcessor.ts
> -    const courseCols = [
What was this constant (and the others like it) used for, and why don't we need them anymore?

2023-04-20 04:53 UTC, Lucas-Dunker commented on services/dumpProcessor.ts
> -    const courseCols = [
Additionally, what does `strTransform` and the other similarly named methods do?

2023-04-21 15:15 UTC, hankewyczz commented on services/dumpProcessor.ts
> +    const groupedCourses = _.chunk(processedCourses, 2000);
I'm fine with leaving that in for now - [related reading](https://franciscov.medium.com/dont-let-the-boy-scouts-rule-hinder-pull-requests-8fdfbd4d5686) which sums it up nicely imo

2023-04-21 15:35 UTC, hankewyczz commented on services/dumpProcessor.ts
> -    const courseCols = [
This is used for preparing all of the entries for the upsert. 

Here's the original query: https://github.com/sandboxnu/course-catalog-api/blob/785b0cd429a9cb9f5d80ac6bc8a10ee6743da4ed/services/dumpProcessor.ts#L272-L294

Basically, the `transforms` methods are used to prepare the variables for the SQL query. Normally, Prisma does this for us, but here, we had to manually prepare everything, escape all the strings, convert non-string variables (dates, arrays) to their corresponding SQL string representation.

2023-04-21 15:44 UTC, Lucas-Dunker approved these changes
👍

2023-04-27 20:36 UTC, merged