Refactor how `TermInfos` are handled in the `dumpProcessor`
sandboxnu/course-catalog-api pull request #185
Opened 2023-05-04 00:26 UTC by hankewyczz

# Purpose

_In 2-3 sentences - what does this code actually do, and why?_

Our workflow with regards to `TermInfos` was poorly designed — you'd need two scrapes to populate them in the DB! (spoiler - that was my fault)

Imagine a new term, with ID `3`, was just released

Before, the flow was:
- Each time we run a scrape, the `TermInfo` table was updated 
  - Only the `TermInfo`s with class/section data in the database would be kept
  - However - this was done BEFORE the sections/classes just scraped were added
  - So - at the time of the check, there are no sections/classes with term ID `3`!
  - The class/section data for `3` would be inserted.

Then, the next time we ran a scrape, term `3` would be added. 

This takes care of that (finally).

# Tickets

_What Trello tickets (if any) are associated with this PR?_

- N/A

# Reviewers

Primary reviewer:

- Pick one primary reviewer
  - The team member with the most relevant knowledge about the code area this PR touches
  - **NOT** an author of the PR
  - If the primary reviewer is the project lead, _select two primary reviewers_
    - Goal: facilitate knowledge transfer to other team members
  - Primary reviewers **are required to approve the PR** before it can be merged

**Primary**:

Use the **"Reviewers"** feature in Github

Secondary reviewers:

- Pick as many as appropriate — anyone who would benefit from reading the PR
  - Tag them using their Github usernames below

**Secondary**:

2023-05-04 01:02 UTC, hankewyczz commented on scrapers/classes/parsersxe/bannerv9Parser.ts
> -  /**
This doesn't really concern Banner, so I moved it out of here

2023-05-04 01:02 UTC, hankewyczz commented on services/dumpProcessor.ts
> +    if (deleteOutdatedData) {
Updated the naming to make it clearer and added some comments. Not directly related to the PR, but a minor tweak

2023-05-07 01:00 UTC, Lucas-Dunker requested changes
Great PR, well explained AND with tests 😎 Only revisions I can think of are to fix the linting warnings!

2023-05-08 16:24 UTC, hankewyczz commented
@Lucas-Dunker Generally, for lint warnings - if your changes caused the lint warning, you're responsible. If not, it's probably left for a different PR. In this case, those lint warnings were already there and don't have anything to do with this PR, so we want to leave it for later - don't want PRs to be too cluttered

2023-05-08 17:09 UTC, Lucas-Dunker approved these changes
LGTM 👍

2023-05-13 21:09 UTC, pranavphadke1 approved these changes

2023-05-18 23:46 UTC, merged