Refactor serializers
sandboxnu/course-catalog-api pull request #220
Opened 2024-09-29 08:45 UTC by nickpfeiffer05

# Purpose

Lodash is unnecessary and can be replaced by native features. Serializer methods are better suited as static methods. 

# Tickets

https://github.com/orgs/sandboxnu/projects/20?pane=issue&itemId=80651976

# Contributors

@Anzhuo-W , @nickpfeiffer05 

# Feature List

1. Removed reliance on Lodash in all serializer files
    - The previous serializers used many Lodash functions (.pick, .groupBy, etc.), that can now be replaced easily by modern JS features
    - PR has replaced all old Lodash functions with native JS
2. Conversion to static methods
    - Converted all serializer methods to static
    - Adjusted the use of serializers from instanced-calling to static-calling in `searcher.ts`

# Reviewers

**Primary**:

@ananyaspatil 

**Secondary**:

@mehallhm , @cherman23

2024-10-01 20:21 UTC, mehallhm approved these changes

2024-10-01 20:42 UTC, mehallhm requested changes
Updating line 82 in the serializers/courseSerializer.ts breaks references in graphql/resolvers/class.ts. Updating the later to use the new static implementation of the method should clear the CI

2024-10-02 23:23 UTC, mehallhm approved these changes

2024-10-04 18:03 UTC, elvincheng3 reviewed
Are there any existing tests for the serializers? If so, we should update/add to them for new code changes; if not, we should write tests.

2024-10-04 18:03 UTC, elvincheng3 reviewed
Are there any existing tests for the serializers? If so, we should update/add to them for new code changes; if not, we should write tests.

2024-11-03 21:22 UTC, closed without merging