Infrastructure Documentation
sandboxnu/course-catalog-api pull request #36
Opened 2021-07-29 03:17 UTC by megandouli

2021-08-16 19:35 UTC, andrewydai approved these changes
Thanks for the write up on this, makes a lot of sense to me

2021-08-28 22:56 UTC, gamburgm requested changes
This is excellent! I noted a couple of things that came to mind. Content is fantastic. Great work!

2021-08-28 22:56 UTC, gamburgm commented on documentation/helpful_commands.md
> +  run these one line at a time to connect to your dev database
I'd put this comment first, lead with why.

2021-08-28 22:56 UTC, gamburgm commented on documentation/helpful_commands.md
> +### Inside The Jumphost (the thing that can connect to the rest of the AWS infrastructure)
Maybe worth defining the jumphost in this document (unless components are documented elsewhere? can't recall)

2021-08-28 22:56 UTC, gamburgm commented on documentation/helpful_commands.md
> +- `DATABASE_URL=<PROD DATABASE URL> elasticURL=<PROD ELASTICSEARCH URL> yarn scrape` to run a production scrape (you have to be in the `course-catalog-api` project inside the Jumphost)
I think it would be clearer to write "you must be at `~/course-catalog-api`."

2021-08-28 22:56 UTC, gamburgm commented on documentation/helpful_commands.md
> +# Some Helpful Commands
I'd restructure a little bit to follow an FAQ format, so it's easier to skim & find relevant commands.

2021-08-28 22:56 UTC, gamburgm commented on documentation/infrastructure/change_staging_url.md
> +1. In `staging.tf`, change `domains` to the desired name.
Might be worth noting when you'd want to change a staging URL?

2021-08-28 22:56 UTC, gamburgm commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +2.  Ask someone on the Sandbox E-Board for the Organization ID (case-sensitive) on your application form. (Note: This is not a promotional code that can be used in your Billing Console)
something about this sounds like you know from experience . . . :thonk:

2021-08-28 22:56 UTC, gamburgm commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +2. Set up the Terraform variables
As an aside, do you know how to add new SSH keys to the jumphost, and do you think that should be written down somewhere?

2021-08-28 22:56 UTC, gamburgm commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +1. Migrate major data into the production database so Graduate doesn't break. Ask someone on the Graduate team for an up-to-date `majors.json` file, put that inside the `./data` directory, and run th
:+1:

2021-08-28 22:56 UTC, gamburgm commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +## Creating the New Infrastructure
I vaguely recall there being issues with Elasticsearch domain domain, hence [this comment](https://github.com/sandboxnu/course-catalog-api/blob/master/infrastructure/terraform/modules/course-catalog-api/elasticsearch.tf#L20). Might be worth mentioning cuz if there are issues you'll definitely need to run it multiple times, and I can't remember for the life of me what we did last time to fix it.

Might be worth noting at the top of this section that "this process is ugly and error-prone, you'll likely run into unexplainable failures and have to run things multiple times. It's okay. Here are some of the errors we've noted and ways we've handled them", etc.

2021-08-28 22:56 UTC, gamburgm commented on documentation/infrastructure/production_scrape.md
> +Imagine this: the scrapers are broken in production, no one knows why, and you NEED to import a fresh scrape to the production database and ElasticSearch (sound familiar?). Here's how to do it.
*sigh*

2021-08-28 22:56 UTC, gamburgm commented on documentation/infrastructure/production_scrape.md
> +3. Unzip the cache inside the `course-catalog-api` project, make sure the unzipped folder is named `cache`.
Some of this overlaps with stuff from the `some_useful_commands` doc, right? might be worth referring to it directly here, still want to follow Single Responsibility Principle to increase maintainability whenever changes need to occur.

2021-08-28 22:56 UTC, gamburgm commented on documentation/infrastructure/production_scrape.md
> +6. **CHANGE THE INSTANCE TYPE BACK TO T2 NANO ONCE THE SCRAPERS FINISH RUNNING TO SAVE $!**
I'm hip

2021-08-29 03:06 UTC, megandouli commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +2. Set up the Terraform variables
actually I don't know how to add new SSH keys to the jumphost lol I gave Andrew mine

2021-08-29 03:26 UTC, megandouli commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +2.  Ask someone on the Sandbox E-Board for the Organization ID (case-sensitive) on your application form. (Note: This is not a promotional code that can be used in your Billing Console)
lmao nah I copy pasted this from something Alex sent when I asked him about getting AWS credits for SearchNEU

2021-08-29 03:39 UTC, gamburgm commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +2. Set up the Terraform variables
Don't do that LOL

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html TL;DR create a key and paste the public key in `~/.ssh/authorized_keys`.

2021-08-29 03:47 UTC, megandouli commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +2. Set up the Terraform variables
bet thanks

2021-08-29 03:51 UTC, megandouli commented on documentation/infrastructure/production_scrape.md
> +3. Unzip the cache inside the `course-catalog-api` project, make sure the unzipped folder is named `cache`.
lol I need to review the SOLID principles

2021-08-30 20:34 UTC, gamburgm approved these changes
:+1: noticed a grammatical error, otherwise, excellent work!

2021-08-30 20:34 UTC, gamburgm commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +Warning: this process is ugly and error-prone, you'll likely run into unexplainable failures and have to run things multiple times. It's okay. Here are some of the steps to take, errors we've ran int
*we've **run** into :^)

2021-08-31 00:53 UTC, megandouli commented on documentation/infrastructure/migrate_infra_new_AWS_account.md
> +Warning: this process is ugly and error-prone, you'll likely run into unexplainable failures and have to run things multiple times. It's okay. Here are some of the steps to take, errors we've ran int
damn those past participles always get me

2021-08-31 00:59 UTC, merged