Twilio
sandboxnu/course-catalog-api pull request #38
Opened 2021-08-27 03:42 UTC by dillonhammer

# Purpose

Rework notifications to use Twilio

<br>

# Tickets

https://trello.com/c/CxbutQVM/209-move-our-notification-system-away-from-facebook-notifications-to-twilio

# Contributors

@dillonhammer
@megandouli 

# Feature List

- Add a server on port 8080 listening for twilio-related requests
   - optional in dev environments; there's a new `dev:notifs` command to run the notification server in dev mode
- Create a signed JWT on successful Twilio phone # verification, check the JWT on every request to add/remove subscriptions
- Add new tables to database to keep track of users and followed courses/sections

# Notes

New environment vars:
```
TWILIO_PHONE_NUMBER
TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN
TWILIO_VERIFY_SERVICE_ID
CLIENT_ORIGIN
JWT_SECRET
```

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [x] Is passing linting checks
- [x] Is passing tsc
- [x] Is passing existing tests
- [x] Has documentation and comments in code
- [x] Has test coverage for code
- [x] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2021-09-24 03:01 UTC, andrewydai requested changes
A general comment is i feel we could have more comments explaining how pieces of code work. However, i'm also not sure how strict we are with that (for example class comments). Ideally I prefer the "Code is self explanatory" style but it's not always possible with complex code.

2021-09-25 20:11 UTC, dfarooq-chwy commented on twilio/server.ts
> +app.get("/knockknock", (req, res) => res.send("Who's there?"));
I was bored and curious so I was poking around for a bit. This actually made me chuckle, thank you 😄

2021-09-25 20:16 UTC, dfarooq610 commented on twilio/server.ts
> +app.get("/knockknock", (req, res) => res.send("Who's there?"));
I was bored and curious so i am poking around. This actually made me chuckle 😄

2021-09-25 22:51 UTC, andrewydai commented on services/notifyer.ts
> +const instance = new Notifyer();
I read about this later and I now understand this is a common singleton pattern in TS/JS. I'm still not sure how i feel about it's necessity if there's no properties on the class but up to you

2021-09-29 15:43 UTC, andrewydai approved these changes
Thanks for all the hard work!

2021-09-29 21:48 UTC, merged