Remove hardcoded term IDs
sandboxnu/course-catalog-api pull request #50
Opened 2021-11-07 21:40 UTC by hankewyczz

https://trello.com/c/xRH6xepp/216-remove-hardcoded-termids

2021-11-08 20:49 UTC, hankewyczz commented on prisma/migrations/20211024221117_reset_term_ids/migration.sql
> +ALTER TABLE "term_ids" ADD COLUMN     "sub_college" TEXT NOT NULL,
Merged

2021-11-08 21:14 UTC, hankewyczz commented on scrapers/classes/parsersxe/bannerv9Parser.js
> +    });
1. Thanks for catching that - it use to be an object, not a list. I updated it
2. Any terms in the TermInfo table which no longer have data

ie. If we once had data for a term, but have since lost/removed that data, there's no point in keeping that term (since we can't serve any data for it)

I added a LOT of comments to the function, lmk if it makes sense now.

2021-11-08 21:53 UTC, hankewyczz commented on services/updater.ts
> +    // Scrapes a list of terms IDs (and associated info) from Banner - these are the only ones we want to update
Good point - the updater will never insert new courses, only update existing ones, so there's no need to query Banner for it. 

I have to say, I'm not a huge fan of the scraper logic (specifically, when a new term comes out). Worst case, we could wait a week before the scrapers pick up the new term. Just an idea, but:

- The scraper could run every hour, and just query the Banner terms endpoint
- If the newest term from Banner is in our database, do nothing. Wait for the weekly scrape
- If the newest term from Banner is not in our database, that means a new term has been released and we don't have it. Run a full scrape, then return to the weekly schedule. 

Thoughts?

2021-11-09 02:15 UTC, megandouli requested changes
this is awesome work

2021-11-09 02:15 UTC, megandouli commented on scrapers/classes/parsersxe/bannerv9Parser.js
> +   * Given a list of TermIDs, it updates the term_info table
would be nice if purpose statement is explicit about how it updates the term_info table

2021-11-09 02:15 UTC, megandouli commented on scrapers/classes/parsersxe/bannerv9Parser.js
> +    let existingIds = await prisma.course.groupBy({ by: ["termId"] });
just make it a `const` one-liner instead of a `let` then reassigning it on the next line:

```
const existingIds = (await prisma.course.groupBy({ by: ["termId"] })).map(t => t.termId);
```

2021-11-09 02:15 UTC, megandouli commented on scrapers/classes/parsersxe/bannerv9Parser.js
> +      // Make sure we have a TermInfo for this term
it seems like we should really be using `.find` instead of `.filter` then checking the length of the filtered array is > 0.

2021-11-09 02:15 UTC, megandouli commented on scrapers/classes/parsersxe/bannerv9Parser.js
> +    }
this is a pretty big method... I think you can pull lines 93-124 into a separate method that returns `filteredTermInfos` then use that below to update the database.

2021-11-09 02:15 UTC, megandouli commented on scrapers/classes/parsersxe/bannerv9Parser.js
> +    const filteredTermInfos = fullTermInfoList.slice(
honestly still pretty confused by what `filteredTermInfos` represents, is there not a better name for it? Is it just the terms we're currently updating plus terms we have courses for in our database?

2021-11-09 02:15 UTC, megandouli commented on services/updater.ts
> +    this.SEMS_TO_UPDATE = termIds;
you'll also need to update `updater.test.seq.ts` since we hard coded `SEMS_TO_UPDATE` there

2021-11-09 19:21 UTC, hankewyczz commented on scrapers/classes/parsersxe/termListParser.js
> +      return "None";
https://github.com/sandboxnu/course-catalog-api/blob/master/scrapers/classes/parsersxe/termListParser.js#L11-L14

The original term parser left the subcollege as undefined for undergrad, but we needed a string for insertion into the database, so we chose "None" (to keep it close to the prior 'undefined' behavior). Switching to "NEU" would be clearer - we just weren't sure if we wanted to keep the 'undefined' behavior

2021-11-09 23:41 UTC, megandouli commented on scrapers/classes/parsersxe/termListParser.js
> +      return "None";
I'm good with switching to "NEU"

2021-11-09 23:44 UTC, megandouli commented on prisma/schema.prisma
> +  subCollege      String   @map(name: "sub_college")
hmmm now that I think about it more, is there any reason we want to store "subCollege" and "text" in our database? it should be possible to derive those values from just the termId, right? Last digit tells you the subCollege and whether it's quarter or semester and second to last digit tells you the season

2021-11-09 23:44 UTC, megandouli commented on scrapers/classes/parsersxe/termListParser.js
> +      return "None";
also just realized we can determine the subcollege in a less hacky way - just use the last digit of the termID

2021-11-10 02:11 UTC, megandouli commented on scrapers/main.js
> +    const allTermInfos = bannerv9parser.getAllTermInfos(bannerv9CollegeUrls[0]);
move to dump processor main func

2021-11-10 02:11 UTC, megandouli commented on services/dumpProcessor.ts
> +        termId: { notIn: Array.from(termIds) },
why do we have array.from here?

2021-11-10 02:11 UTC, megandouli commented on services/dumpProcessor.ts
> +        where: { termId: termId },
kv pairs can be simplified to the common name

2021-11-10 02:11 UTC, megandouli commented on services/updater.ts
> +  // The constructor should never be directly called - use .create()
add comment explaining why this constructor can't be private (but still shouldn't be used)

2021-11-14 22:52 UTC, megandouli approved these changes
amazing work, just one small change then it's good to merge!

2021-11-14 22:52 UTC, megandouli commented on graphql/resolvers/class.ts
> +  const results: Course[] = await prisma.course.findMany({
these type annotations aren't accurate... ideally we'd be able to use prisma generated types but it seems to have stopped working and I believe the fix is upgrading our version of typescript. This `Course` type you imported does not have a sections field but you can see on line 28 the returned object would have sections. For now, just remove these types.

2021-11-17 00:37 UTC, andrewydai approved these changes

2021-11-17 00:37 UTC, andrewydai commented on twilio/server.ts
> +    .catch(() =>
why is this part of this pr lol

2021-11-17 00:48 UTC, hankewyczz commented on twilio/server.ts
> +    .catch(() =>
it was just a linting thing (unused variable)

2021-11-19 01:33 UTC, merged