CPS/LAW term filter
sandboxnu/course-catalog-api pull request #55
Opened 2021-11-22 23:12 UTC by SimChadha

Added term halves for each course to know if they run in the first half, the second half, or the full term. A term half attribute is added to each course in the database after being scraped.

2021-11-27 16:05 UTC, megandouli requested changes

2021-11-27 16:05 UTC, megandouli commented on scrapers/classes/parsersxe/sectionParser.js
> +        ) {
it'd be helpful to declare constants for things like `firstHalfDatesMap[suffix][0]` and `SR.meetingsFaculty[0].meetingTime.startDate.substring(0, 2)` and give those a helpful name. Maybe even a helper function that takes `SR` and returns the month of the start date and end date or something

2021-11-27 16:05 UTC, megandouli commented on scrapers/main.js
> +      console.log(error);
use `macros.log` and `macros.error`

2021-11-27 16:05 UTC, megandouli commented on scrapers/main.js
> +    console.log("Finished Scraping");
use `macros.log`

2021-11-27 19:17 UTC, megandouli reviewed
also merge from master and resolve conflicts on your branch first before merging back into master

2021-12-02 17:16 UTC, hankewyczz requested changes

2021-12-02 17:16 UTC, hankewyczz commented on scrapers/classes/parsersxe/sectionParser.js
> +        const firstHalfDatesMap = {
Same as Megan's comment above - all of the term variables should be maintained in a single file, just to have a single source of truth. I think it'd be worth creating a top-level `vars` directory, and create a file underneath it for the terms (there are other things that should probably be global variables, so it allows us to expand in the future).

2021-12-02 17:16 UTC, hankewyczz commented on scrapers/classes/parsersxe/sectionParser.js
> +        ) {
Adding on to this - a good place for this may be `scrapers/classes/parsersxe/meetingParser`. That's where we do most of the meeting/time parsing, so adding a function there to get the month from an SR object might not be a bad idea.

2021-12-02 17:16 UTC, hankewyczz commented on scrapers/classes/parsersxe/sectionParser.js
> +      termHalf: this.getTermHalf(SR, SR.term),
Should `getTermHalf` maybe be in `MeetingParser`? My logic is:
- This file (where it currently is) doesn't have a lot of parsing methods (imports most of them), so I'd prefer to keep that consistent
- Some of the other parsers (like for profs, meetings, etc) already have parsers in `MeetingParser`, and I feel like getting the term half is related enough to meetings where it justifies the connection

2023-12-03 21:02 UTC, closed without merging