Fix Elasticsearch employee insertion
sandboxnu/course-catalog-api pull request #85
Opened 2022-02-22 02:00 UTC by hankewyczz

# Purpose
Fixes insertion of employees (and by extension, professor search cards)
Also adds tests to ensure this behavior doesn't regress. 
<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- https://trello.com/c/HmL8jG6w/91-professor-card-missing

# Contributors

###### Anyone who contributed to this PR for future reference.

- @hankewyczz 
- @dillonhammer 

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-02-22 03:07 UTC, andrewydai approved these changes
Did you intend to comment out all the tests? Code change looks good

2022-02-22 03:21 UTC, hankewyczz commented
Yep, I started writing the tests, then realized that they're useless until employee scraping is fixed.

2022-03-03 00:46 UTC, hankewyczz commented
Coveralls only reports the coverage change from the first commit, which is kinda sucky, but the coverage went up

2022-03-03 15:43 UTC, andrewydai requested changes
Looks great! I left some comments. Also I know you didn't do type it as `any` for `processProf` but since we have the type `EmployeeWithId[]` it should be the type for profDump and we can maybe type its argument with it for a quick type check win

2022-03-03 15:43 UTC, andrewydai commented on scrapers/employees/employees.ts
> +        emails: [employee.Email],
I think we should change the professor table with a migration to not have emails if it's not included in the response from the new scraping endpoint and we're blowing away old data too

2022-03-03 15:43 UTC, andrewydai commented on scrapers/employees/employees.ts
> +    macros.verbose("neu employee got x-csrf token", xcsrfToken);
NIT but could capitalize the neu since we did it earlier in the `getCsrfToken` method

2022-03-03 15:43 UTC, andrewydai commented on scrapers/employees/employees.ts
> +    const xcsrfToken = await this.getCsrfToken();
I'm guessing the token doesn't expire while scraping since there isn't much logic to handle that. I'm wondering if it might be easier to just do `this.csrftoken` if we already instantiate it in main so that it's cached. I guess I see arguments for both tho as using the method feels safer even though I'm not sure it is (csrftoken doesn't get set to null again and there's no catch for if the response for scraping or csrftoken fails).

2022-03-04 20:02 UTC, hankewyczz commented on scrapers/employees/employees.ts
> +        emails: [employee.Email],
Some of the department-specific webpages actually have multiple emails, so this should be kept at the moment. 

That does bring up a good point about department-specific scraping - why bother? Take `bigPictureUrl` for example - only the CCIS site actually has this attribute. We don't use it for the employee cards, so we're scraping it and not using it. 

There might be a reason for this that I'm unaware of, but I'm in favor of not using the department-specific scrapers. It's more code to maintain, complicates our process, and doesn't add much value as far as I can tell.

2022-03-04 21:27 UTC, andrewydai commented on scrapers/employees/employees.ts
> +        emails: [employee.Email],
Fair point, might be worth ditching them if we can get all data necessary for employees from this new api. Also i'm assuming that all the employees NEU has are listed here, and we won't miss any employees by not scraping departments (that would be my main concern but i'd be surprised if it was true)

2022-03-06 07:32 UTC, megandouli commented on scrapers/employees/employees.ts
> +      apiVersion: "ad_141F5PYcK3c+D5K8O+g",
nit: can we add comments here explaining where we got these values from?

2022-03-06 07:54 UTC, megandouli approved these changes

2022-03-10 23:42 UTC, andrewydai approved these changes

2022-03-13 00:26 UTC, merged