add phrase searching to searcher
sandboxnu/course-catalog-api pull request #95
Opened 2022-03-10 23:57 UTC by sebwittr

# Purpose

###### A brief description of the purpose of the PR's changes for the project.
Added the capabilities for phrase searching to the project. If a query has a phrase within quotes, the searcher will search using a match_phrase query. Every result must contain the contents of a phrase. 

To replicate locally, run yarn dev on the backend, and yarn dev:fullstack on the front end. You can search data structures, and see that discrete structures comes before it. If you search "data structures", it'll be the only result on the page. 
<br> 

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- https://trello.com/c/lYrJEVja/269-add-phrase-searching

# Contributors

###### Anyone who contributed to this PR for future reference.

- @sebwittr 
- @andrewydai 

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

- Added a parser function to the searcher, which broke down queries to phrase queries and non-phrase queries
- Created a QueryWithType type, which was either "phrase" or "most_fields".
- New query structure requires result to include phrase, and should have any other terms.

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-03-12 05:45 UTC, megandouli commented on services/searcher.ts
> +    console.log(JSON.stringify(queries[0]));
remove?

2022-03-12 05:48 UTC, megandouli commented on services/searcher.ts
> +   * else.
did you mean to include `else.`?

2022-03-12 05:48 UTC, megandouli commented on services/searcher.ts
> +   * Most_field queries are everything else, and search the terms on all fields.
nice comment!

2022-03-12 05:49 UTC, megandouli commented on services/searcher.ts
> +    const ret = [];
nit: rename `ret` to `queries`

2022-03-12 05:51 UTC, megandouli commented on services/searcher.ts
> +  parseQuery(query: string): QueryWithType[] {
let's add a unit test for `parseQuery` so we can ensure the quote stuff is correct

2022-03-12 05:56 UTC, megandouli commented on services/searcher.ts
> +    }
instead of all this logic examining character by character, I think we can use regex matching to extract phrases inside quotes - this regex should work: `"/(.*?)"/g` - I grabbed it from https://www.regextester.com/97161

2022-03-12 05:59 UTC, megandouli commented on services/searcher.ts
> +    let fieldStr = "";
I think it'd be cleaner to make `fieldStr` an array of strings and do a `.join(" ")` at the end. Seems better than having to manually concatenate strings with a space everytime

2022-03-12 06:02 UTC, megandouli commented on services/searcher.ts
> +    for (let i = 0; i < queryArr.length; ++i) {
we don't actually need the index here so it'd more idiomatic to do `queryArr.forEach(element => {...})`

2022-03-12 06:03 UTC, megandouli submitted a review, later dismissed
cool feature! minor javascript things that could be improved

2022-03-12 22:23 UTC, hankewyczz requested changes
Generally looks good - just Megan's comments (I didn't see anything needing tweaks besides those)

2022-03-12 22:23 UTC, hankewyczz commented on services/searcher.ts
> +    }
Piggy-backing off of this - I can't think of a straightforward way of matching the obvious. 

So, to get the non-quoted queries:
```
const matches = str.match(/"(.*?)"/gi);
const re = new RegExp(matches.join('|'), 'gi');
const non_matches = str.replace(re, '');
```
Note that this will leave the `"`'s behind, so we should probably strip them out as well.

2022-04-10 23:41 UTC, hankewyczz requested changes
Just a few more tweaks

2022-04-10 23:41 UTC, hankewyczz commented on services/searcher.ts
> +    }
```suggestion
    let matches = query.matchAll(/"(.*?)"/gi) || [];
```

2022-04-10 23:41 UTC, hankewyczz commented on services/searcher.ts
> +   * else.
Was marked as resolved but the comment's still there

2022-04-10 23:41 UTC, hankewyczz commented on services/searcher.ts
> +    const non_matches = query
```suggestion
    const nonMatches = query
```
Case consistency

2022-04-10 23:41 UTC, hankewyczz commented on services/searcher.ts
> +    }
```suggestion
    const phraseQueries = matches.map((match) => {
        return {
          multi_match: {
            query: match[1],
            type: "phrase",
            fields: this.getFields(),
          },
        }
    });
```

The way `matchAll` works: for each match, it returns an array of matches. 

Each match contains, in order:
- The full match
- Any capturing groups (which on our case, is everything but the quotes)


Make sure to test this, since I'm just writing this code in github and haven't 100% checked it

2022-04-12 02:27 UTC, megandouli commented on services/searcher.ts
> +    const re = new RegExp(matches.join("|"), "gi");
nit: rename `re` to `matchesRegExp`? `re` isn't very clear

2022-04-12 02:28 UTC, megandouli commented on services/searcher.ts
> +    const fieldQExists = fieldQuery !== null;
nit: call this `fieldQueryExists` - shortening this variable name is not worth the cost of understandability on line 329

2022-04-12 02:29 UTC, megandouli reviewed
nice! I'll leave it to @hankewyczz to approve but overall looks good to me (just a couple minor nits)

2022-04-21 22:24 UTC, hankewyczz approved these changes
🚀

2022-04-21 22:25 UTC, andrewydai approved these changes
👑

2022-04-22 00:00 UTC, merged