Delete old courses
sandboxnu/course-catalog-api pull request #99
Opened 2022-04-03 19:09 UTC by hankewyczz

# Purpose

###### A brief description of the purpose of the PR's changes for the project.

<br> 

Actually implement [this ticket ](https://trello.com/c/NrnPz8Om/309-old-courses-not-being-deleted)(and add tests to make sure it works lol)

# Tickets

###### A link to any tickets this PR is associated with on Trello.

- https://trello.com/c/NrnPz8Om/309-old-courses-not-being-deleted

# Contributors

###### Anyone who contributed to this PR for future reference.

- @hankewyczz 

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

This would fail on updates, but worked on scrapes. The reason being - we only took into account the termIds of the classes, not the sections. Since the updater doesn't consider classes (only sections), no old sections were being deleted. 

# Checklist

- [x] Filled out PR template :wink:
- [x] Approved by designers
- [ ] Is passing linting checks
- [ ] Is passing tsc
- [ ] Is passing existing tests
- [ ] Has documentation and comments in code
- [ ] Has test coverage for code
- [ ] Will have clear squash commit message

<br>
@sandboxnu/searchneu

2022-04-03 20:45 UTC, hankewyczz commented
> [![Coverage Status](https://camo.githubusercontent.com/dd333678cf30a50a3e359fa93974af9b0efe5f46ffb5bbd5d2adcd2d056209ce/68747470733a2f2f636f766572616c6c732e696f2f6275696c64732f34373935303538342f6261646765)](https://coveralls.io/builds/47950584)
> 
> Coverage decreased (-24.02%) to 30.832% when pulling **[b957709](https://github.com/sandboxnu/course-catalog-api/commit/b9577097b960ba5455f17fb236eb8ce96da03a18) on zh/fix-outdated-section-deletion** into **[86dc41c](https://github.com/sandboxnu/course-catalog-api/commit/86dc41c2d36adeec89b276214bea625059d231e7) on master**.

fake news

2022-04-05 14:51 UTC, andrewydai requested changes
🏎️  i'm just doing random emojis but left a comment

2022-04-05 14:51 UTC, andrewydai commented on tests/workflow_tests/updater.test.git.ts
> +    expect(res.data?.search.nodes[0].sections.length).toBe(3);
kinda small but i'd like this test to specifically check that that section isn't there. Just from following the code change it looks like 2 sections are inserted then 1 is removed via updater. As a result testing that 3 sections exist doesn't seem immediately clear to me as a test of 1900's class being not there.

2022-04-19 06:25 UTC, megandouli commented on services/dumpProcessor.ts
> +  processCourse(classInfo: any): Prisma.CourseCreateInput {
it looks like `processCourse` isn't being used for anything - can we delete?

2022-04-19 06:25 UTC, megandouli commented on services/updater.ts
> +    if (!process.env.UPDATE_ONLY_ONCE) {
instead of a new flag here, can we just check `macros.test`?

2022-04-19 19:11 UTC, hankewyczz commented on services/dumpProcessor.ts
> +  processCourse(classInfo: any): Prisma.CourseCreateInput {
Moving it into the tests - we use it to prepare course objects for a few tests

2022-04-19 19:46 UTC, hankewyczz commented on services/updater.ts
> +    if (!process.env.UPDATE_ONLY_ONCE) {
Parts of the workflow functionality depend on the node_env being `dev`, so changing to test isn't ideal.

2022-04-20 01:18 UTC, megandouli approved these changes

2022-04-20 22:13 UTC, merged